# Generated by Django 4.0.5 on 2022-06-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='designtions',
            field=models.CharField(choices=[('Associate Engineer', 'Associate Engineer'), ('Trainee Engineer', 'Trainee Engineer'), ('Engineer', 'Engineer')], default='Emplyee', max_length=30),
        ),
    ]
