# Generated by Django 4.0.5 on 2022-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='designtions',
            field=models.CharField(choices=[('Associate Engineer', 'Associate Engineer'), ('Engineer', 'Engineer'), ('Trainee Engineer', 'Trainee Engineer')], default='Emplyee', max_length=30),
        ),
    ]
