# Generated by Django 4.0.5 on 2022-06-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_employeeuser_designtions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='designtions',
            field=models.CharField(choices=[('Trainee Engineer', 'Trainee Engineer'), ('Associate Engineer', 'Associate Engineer'), ('Engineer', 'Engineer')], default='Emplyee', max_length=30),
        ),
    ]
